# Supabase Edge Functions configuration
[functions.todos]
verify_jwt = true

[functions.swift-processor]
enabled = true
verify_jwt = false
import_map = "./functions/swift-processor/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/swift-processor/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/swift-processor/*.html" ]

[functions.shopify-webhook]
verify_jwt = false

[functions.create-bosta-delivery]
verify_jwt = true

[functions.bosta-webhook]
verify_jwt = false

[functions.manage-bosta-delivery]
enabled = true
verify_jwt = false
import_map = "./functions/manage-bosta-delivery/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/manage-bosta-delivery/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/manage-bosta-delivery/*.html" ]
